require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/frameworks", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Framework. As you add validations to Framework, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Framework.create! valid_attributes
      get frameworks_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      framework = Framework.create! valid_attributes
      get framework_url(framework)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_framework_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      framework = Framework.create! valid_attributes
      get edit_framework_url(framework)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Framework" do
        expect {
          post frameworks_url, params: { framework: valid_attributes }
        }.to change(Framework, :count).by(1)
      end

      it "redirects to the created framework" do
        post frameworks_url, params: { framework: valid_attributes }
        expect(response).to redirect_to(framework_url(Framework.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Framework" do
        expect {
          post frameworks_url, params: { framework: invalid_attributes }
        }.to change(Framework, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post frameworks_url, params: { framework: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested framework" do
        framework = Framework.create! valid_attributes
        patch framework_url(framework), params: { framework: new_attributes }
        framework.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the framework" do
        framework = Framework.create! valid_attributes
        patch framework_url(framework), params: { framework: new_attributes }
        framework.reload
        expect(response).to redirect_to(framework_url(framework))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        framework = Framework.create! valid_attributes
        patch framework_url(framework), params: { framework: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested framework" do
      framework = Framework.create! valid_attributes
      expect {
        delete framework_url(framework)
      }.to change(Framework, :count).by(-1)
    end

    it "redirects to the frameworks list" do
      framework = Framework.create! valid_attributes
      delete framework_url(framework)
      expect(response).to redirect_to(frameworks_url)
    end
  end
end
