development:
  adapter: redis
  url: redis://localhost:6379/
  host: redis

test:
  adapter: test
  url: redis://localhost:6379/
  host: redis

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: asessment_tool_point_b_production
